import {
  mdiAlbum,
  mdiAnchor,
  mdiContentSave,
  mdiCrownOutline,
  mdiGamepad,
  mdiGlassCocktail,
  mdiHeartOutline,
  mdiLightbulbFluorescentTubeOutline,
  mdiLingerie,
  mdiPill,
  mdiPistol,
  mdiRacingHelmet,
  mdiSpaceInvaders,
  mdiSpeaker,
  mdiSunglasses,
  mdiWeatherSunset,
} from '@mdi/js'

export const iconPathList = [
  mdiAlbum,
  mdiAnchor,
  mdiContentSave,
  mdiCrownOutline,
  mdiGamepad,
  mdiGlassCocktail,
  mdiHeartOutline,
  mdiLightbulbFluorescentTubeOutline,
  mdiLingerie,
  mdiPill,
  mdiPistol,
  mdiRacingHelmet,
  mdiSpaceInvaders,
  mdiSpeaker,
  mdiSunglasses,
  mdiWeatherSunset,
]
